
const propiedades = [
    {
        tituloPropiedad: "La Cabaña",
        descripcionPropiedad: "Gran cabaña en la Montaña",
        habitacionesPropiedad: 4,
        estacionamientoPropiedad: 1,
        wcPropiedad: 3,
        calle: "Encino 607",
        lat: "20.68348828735",
        lng: "-103.386891327513",
        imagen: "1.jpg",
        publicado: 0,
        llaveForaneaPrecio: 3,
        llaveForaneaCategoria: 2,
        llaveForaneaUsuario: 1
    },
    {
        tituloPropiedad: "La mansion",
        descripcionPropiedad: "Gran casa blanca al lado de plaza.",
        habitacionesPropiedad: 4,
        estacionamientoPropiedad: 1,
        wcPropiedad: 3,
        calle: "Encino 607",
        lat: "20.686248",
        lng: "-103.3851",
        imagen: "2.jpg",
        publicado: 0,
        llaveForaneaPrecio: 5,
        llaveForaneaCategoria: 3,
        llaveForaneaUsuario: 1
    },
    {
        tituloPropiedad: "La estancia",
        descripcionPropiedad: "Casa en la Playa",
        habitacionesPropiedad: 2,
        estacionamientoPropiedad: 0,
        wcPropiedad: 2,
        calle: "Frambroyan 607",
        lat: "20.68265707123",
        lng: "-103.382210697427",
        imagen: "3.jpg",
        publicado: 0,
        llaveForaneaPrecio: 7,
        llaveForaneaCategoria: 1,
        llaveForaneaUsuario: 1
    },
    {
        tituloPropiedad: "Casa de Descanso",
        descripcionPropiedad: "Pequeña casa a a las afueras",
        habitacionesPropiedad: 1,
        estacionamientoPropiedad: 1,
        wcPropiedad: 1,
        calle: "Casa del niño 607",
        lat: "20.678925",
        lng: "-103.3800552",
        imagen: "4.jpg",
        publicado: 0,
        llaveForaneaPrecio: 4,
        llaveForaneaCategoria: 1,
        llaveForaneaUsuario: 3
    },
    {
        tituloPropiedad: "Casa de Verano",
        descripcionPropiedad: "Casa de dos pisos con muy buena ubicación",
        habitacionesPropiedad: 2,
        estacionamientoPropiedad: 1,
        wcPropiedad: 3,
        calle: "Lazaro Cardenas 508",
        lat: "20.675753006095",
        lng: "-103.382265019874",
        imagen: "5.jpg",
        publicado: 0,
        llaveForaneaPrecio: 7,
        llaveForaneaCategoria: 1,
        llaveForaneaUsuario: 2
    },
    {
        tituloPropiedad: "Terreno Valdio",
        descripcionPropiedad: "Terreno de 16 metros a cuadrados",
        habitacionesPropiedad: 0,
        estacionamientoPropiedad: 0,
        wcPropiedad: 0,
        calle: "Emiliano Zapata 8",
        lat: "20.672650905639",
        lng: "-103.383861101877",
        imagen: "6.jpg",
        publicado: 0,
        llaveForaneaPrecio: 3,
        llaveForaneaCategoria: 4,
        llaveForaneaUsuario: 1
    },
    {
        tituloPropiedad: "Departamento",
        descripcionPropiedad: "Gran departamento en zona metropolitana",
        habitacionesPropiedad: 2,
        estacionamientoPropiedad: 0,
        wcPropiedad: 1,
        calle: "Av. Vallarta 8",
        lat: "20.670264698885",
        lng: "-103.387800745564",
        imagen: "7.jpg",
        publicado: 0,
        llaveForaneaPrecio: 5,
        llaveForaneaCategoria: 2,
        llaveForaneaUsuario: 3
    },
    {
        tituloPropiedad: "Bodega",
        descripcionPropiedad: "Bodega pequeña en zona de mercado",
        habitacionesPropiedad: 0,
        estacionamientoPropiedad: 0,
        wcPropiedad: 1,
        calle: "Av. Juarez 8",
        lat: "20.670264698885",
        lng: "-103.39108496131",
        imagen: "8.jpg",
        publicado: 0,
        llaveForaneaPrecio: 2,
        llaveForaneaCategoria: 4,
        llaveForaneaUsuario: 2
    },
    {
        tituloPropiedad: "Cabaña",
        descripcionPropiedad: "Cabaña en medio de bosque",
        habitacionesPropiedad: 1,
        estacionamientoPropiedad: 2,
        wcPropiedad: 2,
        calle: "Bosque Patzcuaro 8",
        lat: "20.669368174232",
        lng: "-103.394248711849",
        imagen: "9.jpg",
        publicado: 0,
        llaveForaneaPrecio: 5,
        llaveForaneaCategoria: 5,
        llaveForaneaUsuario: 1
    },
    {
        tituloPropiedad: "Cabaña Negra",
        descripcionPropiedad: "Orilla del lago",
        habitacionesPropiedad: 1,
        estacionamientoPropiedad: 3,
        wcPropiedad: 2,
        calle: "Bosque Quiroga 8",
        lat: "20.666550187376",
        lng: "-103.395621322236",
        imagen: "10.jpg",
        publicado: 0,
        llaveForaneaPrecio: 8,
        llaveForaneaCategoria: 5,
        llaveForaneaUsuario: 3
    },
    {
        tituloPropiedad: "Hogar de Grandes",
        descripcionPropiedad: "Casa en zona Residencial",
        habitacionesPropiedad: 3,
        estacionamientoPropiedad: 1,
        wcPropiedad: 2,
        calle: "Av. Patria 8",
        lat: "20.662555361035",
        lng: "-103.398505488647",
        imagen: "11.jpg",
        publicado: 0,
        llaveForaneaPrecio: 8,
        llaveForaneaCategoria: 5,
        llaveForaneaUsuario: 2
    }

]

export default propiedades;